# 5_ruby_env.yml
#   Setup server with a ruby on rails env
#
# Details:
# - Install App required packages
# - Install NodeJS and yarn - used by canvas lms
# - Install rvm and ruby

- name: App Server system setup
  hosts: app
  become: yes
  tasks:
    ###
    # System required packages
    ###
    - name: Install required packages
      tags:
        - update-packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - software-properties-common
          - zlib1g-dev
          - libxml2-dev
          - libsqlite3-dev
          - libpq-dev
          - libxmlsec1-dev
          - curl
          - make
          - g++
          - gcc
          - imagemagick
          - libmagick++-dev
          - gnupg2
          - dirmngr

    ###
    # node setup
    ###
    - name: Add Nodesource keys
      tags:
        - update-node
      apt_key:
        url: '{{ item }}'
        state: present
      with_items:
        - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        - https://dl.yarnpkg.com/debian/pubkey.gpg

    - name: Add Nodesource APT repos
      apt_repository:
        repo: '{{ item }}'
        state: present
      with_items:
        - "deb https://deb.nodesource.com/node_{{nodejs_version}} {{ ansible_distribution_release }} main"
        - "deb-src https://deb.nodesource.com/node_{{nodejs_version}} {{ ansible_distribution_release }} main"
        - "deb https://dl.yarnpkg.com/debian/ stable main"

    - name: Install NodeJS and yarn
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - nodejs
          - yarn

###
# Ruby installation through rvm
###

# Every commented line here could be uncommented for a system install
# Look in playbooks/roles/rvm1-ansible README file for more info
- name: Configure servers with ruby support
  hosts: app
  become: yes

  roles:
    - {
      role: rvm1-ansible,
      tags: ruby,
      # become: yes,

      rvm1_gpg_keys: "{{ rvm_gpg_key }}",
      rvm1_rubies: ["{{ ruby_version }}"],
      rvm1_install_flags: '--auto-dotfiles --user-install',
      rvm1_user: "{{ app_service_account }}",
      rvm1_install_path: "/home/{{ app_service_account }}/.rvm",
      #rvm1_user: root
    }

  tasks:
    # - name: Add users to rvm group
    #   user:
    #     name: "{{ item }}"
    #     groups: rvm
    #   with_items:
    #     - "{{ app_service_account }}"
    #     - "{{ server_admin_account }}"

    - name: Deploy .gemrc
      tags:
        - update-gems
        - update-ruby
      copy: src=templates/gemrc dest=~/.gemrc
      become_user: "{{ item }}"
      with_items:
        - "{{ app_service_account }}"
        #- "{{ server_admin_account }}"

    - name: Ensure bundler gem is installed in right version
      tags:
        - update-ruby
        - update-gems
      become_user: "{{ app_service_account }}"
      gem: name={{ item.name }} version={{ item.version }} user_install=no
      with_items: "{{ base_gems }}"
